venmo link
digitalaidseattle/digital-aid-seattle-website pull request #181
Opened 2024-10-03 15:01 UTC by jnakaso

## What

> Added link to venmo payment
> updated donation text

## Why Do

> More variety of payment forms

## Show Me

<img width="982" alt="Screenshot 2024-10-03 at 8 00 29 AM" src="https://github.com/user-attachments/assets/0eb07b2d-2116-4cc3-babb-0dcd41a61a41">

2024-10-03 21:39 UTC, ybalenko requested changes
@jnakaso there are two issues happening in Chrome, please check your Inbox.

2024-10-04 21:25 UTC, jnakaso commented
> @jnakaso there are two issues happening in Chrome, please check your Inbox.

@ybalenko I'm unable to reproduce the issue

2024-10-08 04:28 UTC, ybalenko commented
It's good to go! @jnakaso

2024-10-08 04:28 UTC, ybalenko approved these changes

2024-10-08 04:51 UTC, merged